<a href="https://colab.research.google.com/github/Kashaf-Abdullah/llm-internals-and-finetuning/blob/main/LLM_Internals_And_FineTuning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install requests==2.32.4

In [4]:
# Import requests to send HTTP requests to the Groq API
import requests

# Import time to measure how long the API request takes
import time

# Import getpass to securely enter the API key without displaying it
from getpass import getpass


# Ask the user to enter their Groq API key securely
GROQ_API_KEY = getpass("Enter Groq API key: ")


# Store the Groq API endpoint URL
url = "https://api.groq.com/openai/v1/chat/completions"


# Create HTTP headers required by the API
headers = {
    # Send the API key to authenticate the request
    "Authorization": f"Bearer {GROQ_API_KEY}",

    # Tell the API that we are sending JSON data
    "Content-Type": "application/json"
}


# Create the data that will be sent to the Groq API
payload = {

    # Specify which AI model we want to use
    "model": "openai/gpt-oss-20b",

    # Provide the conversation/message for the AI
    "messages": [
        {
            # Define this message as coming from the user
            "role": "user",

            # The actual question/prompt sent to the AI
            "content": "Say hello"
        }
    ],

    # Limit the maximum number of tokens in the AI response
    "max_tokens": 20,

    # Control how random/creative the response should be
    # Lower temperature = more predictable responses
    "temperature": 0.2
}


# Print a message so we know the API request is starting
print("Calling Groq API...")


# Record the current time before making the API request
start = time.time()
try:
    response = requests.post(
        url,
        headers=headers,
        json=payload,
        timeout=15
    )

    print("Status code:", response.status_code)
    print("Time taken:", round(time.time() - start, 2), "seconds")
    print(response.json())

except Exception as e:
    print("Request failed:")
    print(e)

Enter Groq API key: ··········
Calling Groq API...
Status code: 200
Time taken: 0.18 seconds
{'id': 'chatcmpl-f2ef0de8-eea0-44f9-86e0-5f33d52aaf20', 'object': 'chat.completion', 'created': 1790274780, 'model': 'openai/gpt-oss-20b', 'choices': [{'index': 0, 'message': {'role': 'assistant', 'content': '', 'reasoning': 'User says "Say hello". Likely they want a greeting. We should respond with'}, 'logprobs': None, 'finish_reason': 'length'}], 'usage': {'queue_time': 0.005358634, 'prompt_tokens': 73, 'prompt_time': 0.003519723, 'completion_tokens': 20, 'completion_time': 0.022146837, 'total_tokens': 93, 'total_time': 0.02566656, 'completion_tokens_details': {'reasoning_tokens': 18}}, 'usage_breakdown': None, 'system_fingerprint': 'fp_996f667773', 'x_groq': {'id': 'req_01m3ab2fgcedx8b4b4fv46a7md', 'seed': 1051284924}, 'service_tier': 'on_demand'}


In [11]:
# Function to demonstrate how tokenization works
def demo_tokenization():

    # Print a heading line
    print("=" * 60)

    # Print the title of the demo
    print("DEMO: How Tokenization Works")

    # Print another heading line
    print("=" * 60)

    # Dictionary containing example words and their tokens
    # Each word is manually divided into smaller tokens
    examples = {
        "Hello": ["Hello"],
        "Generative": ["Gener", "ative"],
        "Transformer": ["Transform", "er"],
        "Supercalifragilistic": ["Super", "cali", "fragil", "istic"],
        "AI": ["AI"],
        "fine-tuning": ["fine", "-", "tuning"],
        "backpropagation": ["back", "prop", "agation"]
    }

    # Loop through each word and its corresponding tokens
    for word, tokens in examples.items():

        # len(tokens) counts how many tokens the word contains
        # The result is printed along with the word and its tokens
        print(
            f'Word: "{word}" -> {len(tokens)} token(s) -> {tokens}'
        )


# Call the function to run the tokenization demonstration
demo_tokenization()

DEMO: How Tokenization Works
Word: "Hello" -> 1 token(s) -> ['Hello']
Word: "Generative" -> 2 token(s) -> ['Gener', 'ative']
Word: "Transformer" -> 2 token(s) -> ['Transform', 'er']
Word: "Supercalifragilistic" -> 4 token(s) -> ['Super', 'cali', 'fragil', 'istic']
Word: "AI" -> 1 token(s) -> ['AI']
Word: "fine-tuning" -> 3 token(s) -> ['fine', '-', 'tuning']
Word: "backpropagation" -> 3 token(s) -> ['back', 'prop', 'agation']


In [14]:
!pip install groq -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.8/143.8 kB 3.0 MB/s eta 0:00:00


In [37]:
from groq import Groq
from getpass import getpass

# Enter your Groq API key
GROQ_API_KEY = getpass("Enter your Groq API key: ")

# Create Groq client
client = Groq(
    api_key=GROQ_API_KEY,
    timeout=20.0,
    max_retries=0
)

print("Groq client is ready!")

# Simple API test
response = client.chat.completions.create(
    model="openai/gpt-oss-20b",
    messages=[
        {
            "role": "user",
            "content": "Say hello in one sentence."
        }
    ],
    max_tokens=50
)

print(response.choices[0].message.content)

Enter your Groq API key: ··········
Groq client is ready!



In [39]:
def demo_self_attention():
    print("=" * 60)
    print("DEMO: Self-Attention Mechanism")
    print("=" * 60)

    print("1. Creating prompt...")

    prompt = """
Demonstrate self-attention with this sentence:

"The trophy did not fit in the suitcase because it was too big."

For each of these tokens: [trophy, suitcase, it, big]

Explain which words they would attend to most strongly and why.

Keep the answer simple and concise.
"""

    print("2. Sending request to Groq...")

    try:
        response = client.chat.completions.create(
            model="openai/gpt-oss-20b",
            messages=[
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            max_tokens=500,
            temperature=0.3
        )

        print("3. Response received!")
        print("-" * 60)
        print(response.choices[0].message.content)
        print("-" * 60)

    except Exception as e:
        print("ERROR:")
        print(type(e).__name__)
        print(e)


demo_self_attention()

DEMO: Self-Attention Mechanism
1. Creating prompt...
2. Sending request to Groq...
3. Response received!
------------------------------------------------------------
**Self‑attention highlights (simplified)**  

| Token | Words it would attend to most strongly | Why |
|-------|----------------------------------------|-----|
| **trophy** | *fit*, *big* | “trophy” is the subject of the verb *fit* and is described by the adjective *big*. |
| **suitcase** | *fit*, *trophy* | “suitcase” is the object of the verb *fit* and is the noun that “trophy” is being compared to. |
| **it** | *trophy* | The pronoun “it” refers back to the noun “trophy”, so it focuses on that word. |
| **big** | *trophy* | “big” modifies “trophy”, so it attends to the noun it describes. |

These are the strongest links a self‑attention layer would learn for each of the four tokens.
------------------------------------------------------------


In [44]:
def demo_architecture_types():
    # Print heading
    print("=" * 60)
    print("DEMO: Encoder vs Decoder vs Encoder-Decoder")
    print("=" * 60)

    # Prompt for the AI model
    prompt = """
Explain the best Transformer architecture for each task below.

For each task, answer in exactly 3 bullet points:
• Best architecture: Encoder-only, Decoder-only, or Encoder-Decoder
• Why this architecture is best
• One real model example

Tasks:

1. Classification Task:
Classify this review as positive or negative:
"The product was amazing!"

2. Translation Task:
Translate to French:
"Large language models are powerful."

3. Generation Task:
Continue this story:
"Once upon a time, a robot learned to"

4. Extraction Task:
Extract all named entities from:
"Apple CEO Tim Cook visited Paris."
"""

    # Send the prompt to Groq
    response = client.chat.completions.create(
        model="openai/gpt-oss-20b",
        messages=[
            {
                "role": "user",
                "content": prompt
            }
        ],
        max_tokens=600,
        temperature=0.3
    )

    # Print the AI response
    print(response.choices[0].message.content)


# Run the demonstration
demo_architecture_types()

DEMO: Encoder vs Decoder vs Encoder-Decoder
**1. Classification Task**  
- **Best architecture:** Encoder‑only  
- **Why this architecture is best:** Encoder‑only models efficiently capture contextualized representations of the input text, which can be pooled and fed into a classification head for binary sentiment prediction.  
- **One real model example:** BERT‑Base (Bidirectional Encoder Representations from Transformers)

**2. Translation Task**  
- **Best architecture:** Encoder‑decoder  
- **Why this architecture is best:** The encoder processes the source sentence into a contextual representation, and the decoder generates the target sentence token by token, allowing the model to learn the alignment between source and target languages.  
- **One real model example:** MarianMT (the multilingual translation model from the Hugging Face Transformers library)

**3. Generation Task**  
- **Best architecture:** Decoder‑only  
- **Why this architecture is best:** Decoder‑only models are 

In [54]:
def demo_base_vs_finetuned():

    # ---------------------------------------------------------
    # STEP 1: Print the title
    # ---------------------------------------------------------

    print("=" * 60)
    print("DEMO: Base Model vs Instruction Fine-Tuned Model")
    print("=" * 60)

    # Question given to both model simulations
    test_prompt = "What is the capital of France?"

    # Groq model used for the demonstration
    model_name = "openai/gpt-oss-20b"


    # ---------------------------------------------------------
    # STEP 2: Simulate BASE MODEL behavior
    # ---------------------------------------------------------

    # A base model is trained mainly to predict the next token.
    # It is not specifically trained to follow user instructions.
    #
    # We ask the model to behave like a text-completion model.

    base_model_prompt = f"""
Complete the following text naturally.

Do not explain anything.
Do not answer as a chatbot.
Simply continue the text.

Text:
Question: {test_prompt}
Answer:
"""

    # Send the request to the model
    base_response = client.chat.completions.create(
        model=model_name,
        messages=[
            {
                "role": "user",
                "content": base_model_prompt
            }
        ],
        max_tokens=100,
        temperature=0.8
    )


    # ---------------------------------------------------------
    # STEP 3: Simulate INSTRUCTION FINE-TUNED behavior
    # ---------------------------------------------------------

    # An instruction fine-tuned model is trained to follow
    # instructions and respond directly to the user.

    finetuned_response = client.chat.completions.create(
        model=model_name,
        messages=[
            {
                "role": "system",
                "content": "You are a helpful AI assistant. Answer clearly and directly."
            },
            {
                "role": "user",
                "content": test_prompt
            }
        ],
        max_tokens=100,
        temperature=0.3
    )


    # ---------------------------------------------------------
    # STEP 4: Display the question
    # ---------------------------------------------------------

    print(f"\nQuestion: {test_prompt}")


    # ---------------------------------------------------------
    # STEP 5: Display BASE MODEL simulation
    # ---------------------------------------------------------

    print("\n" + "-" * 60)
    print("BASE MODEL SIMULATION")
    print("-" * 60)

    print("Pre-trained model predicts text continuation:")

    base_text = base_response.choices[0].message.content

    # Check whether the model returned any text
    if base_text and base_text.strip():
        print(base_text)
    else:
        # Fallback message if the instruction-following model
        # returns an empty response
        print("The model did not generate a continuation.")


    # ---------------------------------------------------------
    # STEP 6: Display INSTRUCTION FINE-TUNED response
    # ---------------------------------------------------------

    print("\n" + "-" * 60)
    print("INSTRUCTION FINE-TUNED MODEL")
    print("-" * 60)

    print("Follows the user instruction and answers directly:")

    print(finetuned_response.choices[0].message.content)


    # ---------------------------------------------------------
    # STEP 7: Finish the demonstration
    # ---------------------------------------------------------

    print("\n" + "=" * 60)


# Run the demonstration
demo_base_vs_finetuned()

DEMO: Base Model vs Instruction Fine-Tuned Model

Question: What is the capital of France?

------------------------------------------------------------
BASE MODEL SIMULATION
------------------------------------------------------------
Pre-trained model predicts text continuation:
Paris

------------------------------------------------------------
INSTRUCTION FINE-TUNED MODEL
------------------------------------------------------------
Follows the user instruction and answers directly:
The capital of France is **Paris**.



In [59]:
# DEMO: LoRA (Low-Rank Adaptation) Explained

import numpy as np


def demo_lora_concept():

    print("=" * 60)
    print("DEMO: LoRA (Low-Rank Adaptation) Explained")
    print("=" * 60)

    # ---------------------------------------------------------
    # 1. Original weight matrix
    # ---------------------------------------------------------
    # This represents the original model weights.
    # In this example, the matrix is 4 x 4.
    W = np.array([
        [0.1, 0.2, 0.3, 0.4],
        [0.5, 0.6, 0.7, 0.8],
        [0.9, 1.0, 1.1, 1.2],
        [1.3, 1.4, 1.5, 1.6]
    ])

    # ---------------------------------------------------------
    # 2. LoRA low-rank matrices
    # ---------------------------------------------------------
    # Instead of updating the complete W matrix,
    # LoRA learns two smaller matrices: A and B.

    # A has shape 4 x 1
    A = np.array([
        [0.1],
        [0.2],
        [0.3],
        [0.4]
    ])

    # B has shape 1 x 4
    B = np.array([
        [0.1, 0.2, 0.3, 0.4]
    ])

    # ---------------------------------------------------------
    # 3. Calculate LoRA update
    # ---------------------------------------------------------
    # Matrix multiplication of A and B creates delta_W.
    #
    # A:       4 x 1
    # B:       1 x 4
    # Result:  4 x 4
    #
    # delta_W represents the small change LoRA wants
    # to make to the original weights.
    delta_W = A @ B

    # ---------------------------------------------------------
    # 4. Create updated weight matrix
    # ---------------------------------------------------------
    # The original weights are combined with the LoRA update.
    W_updated = W + delta_W

    # ---------------------------------------------------------
    # Display matrices
    # ---------------------------------------------------------

    print("\nOriginal Weight Matrix W:")
    print(W)

    print("\nLoRA Matrix A:")
    print(A)

    print("A shape:", A.shape)

    print("\nLoRA Matrix B:")
    print(B)

    print("B shape:", B.shape)

    print("\nLoRA Update delta_W = A @ B:")
    print(delta_W)

    print("\nUpdated Matrix W + delta_W:")
    print(W_updated)

    # ---------------------------------------------------------
    # 5. Compare number of parameters
    # ---------------------------------------------------------

    # Full fine-tuning updates every value in W.
    # W contains 4 x 4 = 16 parameters.
    full_params = 4 * 4

    # LoRA only trains A and B.
    # A contains 4 x 1 = 4 parameters.
    # B contains 1 x 4 = 4 parameters.
    # Total = 8 parameters.
    lora_params = (4 * 1) + (1 * 4)

    # Calculate percentage of parameters saved.
    saved_percent = ((full_params - lora_params) / full_params) * 100

    print("\nParameter Count:")
    print(f"Full fine-tuning parameters: {full_params}")
    print(f"LoRA rank-1 parameters: {lora_params}")
    print(f"Parameter saving: {saved_percent:.1f}%")

    # ---------------------------------------------------------
    # 6. Simple explanation
    # ---------------------------------------------------------

    print("\nSimple Explanation:")
    print("Full fine-tuning updates every value in the weight matrix.")
    print("LoRA freezes the original matrix and learns two smaller matrices, A and B.")
    print("These two smaller matrices create a small update called delta_W.")
    print("In real LLMs, this can save a huge amount of memory and training cost.")


# Run the demo
demo_lora_concept()

DEMO: LoRA (Low-Rank Adaptation) Explained

Original Weight Matrix W:
[[0.1 0.2 0.3 0.4]
 [0.5 0.6 0.7 0.8]
 [0.9 1.  1.1 1.2]
 [1.3 1.4 1.5 1.6]]

LoRA Matrix A:
[[0.1]
 [0.2]
 [0.3]
 [0.4]]
A shape: (4, 1)

LoRA Matrix B:
[[0.1 0.2 0.3 0.4]]
B shape: (1, 4)

LoRA Update delta_W = A @ B:
[[0.01 0.02 0.03 0.04]
 [0.02 0.04 0.06 0.08]
 [0.03 0.06 0.09 0.12]
 [0.04 0.08 0.12 0.16]]

Updated Matrix W + delta_W:
[[0.11 0.22 0.33 0.44]
 [0.52 0.64 0.76 0.88]
 [0.93 1.06 1.19 1.32]
 [1.34 1.48 1.62 1.76]]

Parameter Count:
Full fine-tuning parameters: 16
LoRA rank-1 parameters: 8
Parameter saving: 50.0%

Simple Explanation:
Full fine-tuning updates every value in the weight matrix.
LoRA freezes the original matrix and learns two smaller matrices, A and B.
These two smaller matrices create a small update called delta_W.
In real LLMs, this can save a huge amount of memory and training cost.


In [66]:
import numpy as np


def demo_quantization():

    print("=" * 60)
    print("DEMO: Quantization - Memory vs Quality Tradeoff")
    print("=" * 60)

    # Example model weights
    weights = np.array([
        0.1234,
        0.5678,
        0.9123,
        0.3456,
        0.7891
    ])

    print("\nOriginal FP32 Weights:")
    print(weights)

    # FP32 uses 32 bits per value
    print("\nFP32 - Full Precision")
    print("Memory usage: High")
    print("Precision: High")
    print("Example: 0.1234")

    # Simulate FP16
    fp16_weights = weights.astype(np.float16)

    print("\nFP16 - Half Precision")
    print("Memory usage: Lower")
    print("Precision: Slightly lower")
    print("Example:", fp16_weights)

    # Simulate INT8 quantization
    int8_weights = np.round(weights * 127).astype(np.int8)

    print("\nINT8 - 8-bit Quantized")
    print("Memory usage: Low")
    print("Precision: Lower")
    print("Quantized values:", int8_weights)

    # Simulate INT4 quantization
    int4_weights = np.round(weights * 7).astype(np.int8)

    print("\nINT4 - 4-bit Quantized")
    print("Memory usage: Very Low")
    print("Precision: Potentially lower")
    print("Quantized values:", int4_weights)

    print("\n" + "=" * 60)
    print("SUMMARY")
    print("=" * 60)

    print("FP32 → Highest precision, highest memory")
    print("FP16 → Lower memory, good precision")
    print("INT8 → Much lower memory")
    print("INT4 → Very low memory, more compression")

    print("\nKey Idea:")
    print("Quantization reduces the number of bits used to store")
    print("model weights, saving memory at the possible cost of quality.")


# Run the demo
demo_quantization()

DEMO: Quantization - Memory vs Quality Tradeoff

Original FP32 Weights:
[0.1234 0.5678 0.9123 0.3456 0.7891]

FP32 - Full Precision
Memory usage: High
Precision: High
Example: 0.1234

FP16 - Half Precision
Memory usage: Lower
Precision: Slightly lower
Example: [0.1234 0.568  0.912  0.3457 0.789 ]

INT8 - 8-bit Quantized
Memory usage: Low
Precision: Lower
Quantized values: [ 16  72 116  44 100]

INT4 - 4-bit Quantized
Memory usage: Very Low
Precision: Potentially lower
Quantized values: [1 4 6 2 6]

SUMMARY
FP32 → Highest precision, highest memory
FP16 → Lower memory, good precision
INT8 → Much lower memory
INT4 → Very low memory, more compression

Key Idea:
Quantization reduces the number of bits used to store
model weights, saving memory at the possible cost of quality.


In [67]:
def demo_domain_finetuning():

    print("=" * 60)
    print("DEMO: General Model vs Domain Fine-Tuned Model")
    print("=" * 60)

    # Medical question that we will ask both models
    medical_question = "What are the contraindications for metformin use?"

    # ---------------------------------------------------------
    # GENERAL MODEL
    # ---------------------------------------------------------
    # This model is given a general assistant instruction.
    general_response = client.chat.completions.create(
        model="openai/gpt-oss-20b",
        messages=[
            {
                "role": "system",
                "content": "You are a general assistant with broad knowledge."
            },
            {
                "role": "user",
                "content": medical_question
            }
        ],
        max_tokens=200,
        temperature=0.5
    )

    # ---------------------------------------------------------
    # DOMAIN FINE-TUNED MODEL
    # ---------------------------------------------------------
    # Here we simulate a medical fine-tuned model using
    # a specialized system prompt.
    medical_response = client.chat.completions.create(
        model="openai/gpt-oss-20b",
        messages=[
            {
                "role": "system",
                "content": """
You are a medical AI assistant fine-tuned on clinical
literature and pharmacology databases.

Provide precise and structured medical information
using appropriate clinical terminology.

Always structure responses with:
1. Contraindications
2. Clinical Reasoning
3. Monitoring Parameters
"""
            },
            {
                "role": "user",
                "content": medical_question
            }
        ],
        max_tokens=300,
        temperature=0.2
    )

    # ---------------------------------------------------------
    # DISPLAY RESULTS
    # ---------------------------------------------------------

    print(f"\nQuestion: {medical_question}")

    print("\n" + "-" * 60)
    print("GENERAL MODEL RESPONSE:")
    print("-" * 60)

    print(general_response.choices[0].message.content)

    print("\n" + "-" * 60)
    print("DOMAIN FINE-TUNED MODEL RESPONSE (MEDICAL):")
    print("-" * 60)

    print(medical_response.choices[0].message.content)


# Run the demo
demo_domain_finetuning()

DEMO: General Model vs Domain Fine-Tuned Model

Question: What are the contraindications for metformin use?

------------------------------------------------------------
GENERAL MODEL RESPONSE:
------------------------------------------------------------
**Metformin** (glucophage, glumetza, etc.) is a first‑line oral antihyperglycemic agent for type 2 diabetes. While it is generally safe, there are several *absolute

------------------------------------------------------------
DOMAIN FINE-TUNED MODEL RESPONSE (MEDICAL):
------------------------------------------------------------

